<a href="https://colab.research.google.com/github/parv-39/Aum_Basics/blob/main/Numpy_Aum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print(np.__version__) #used to check the version of numpy

myarr = np.array([1,2,3,4]) #create array
print(myarr)#display array

a = np.zeros((4,3)) #array of zeros
print(a)

b = np.ones(4) #array of ones
print(b)

c = np.empty((4,4)) #array of empty
print(c)

2.0.2
[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
 [4.4e-323 4.9e-323 5.4e-323 5.9e-323]
 [6.4e-323 6.9e-323 7.4e-323 7.9e-323]]


In [ ]:
import numpy as np

a = np.array(42) #this is how the 0-D array is declared
b = np.array([1,2,3]) #this is how the 1-D array is declared
c = np.array([[1,2],[3,4]]) #this is how the 2-D array is declared
# d = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #this is how the 3-D array is declared
#or
d = np.array([1,2,3],ndmin=3)


print(a.ndim) #used to check the dimension of array
print(b.ndim) #used to check the dimension of array
print(c.ndim) #used to check the dimension of array
print(d.ndim) #used to check the dimension of array


arr = np.array([1, 2, 3, 4], ndmin=5) #for n-dimensional array
print(arr)
print('number of dimensions :', arr.ndim)

0
1
2
3
[0. 0. 0. 0.] 1
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

#1-D Array
arr = np.array([1,2,3])
print(arr[0]) #used to print the specifix index value from the array
print(arr[1]) #used to print the specifix index value from the array
arr1 = np.array([1,2,3,4])
print(arr1[2] + arr1[3]) #used to add the value of the specified index

#2-D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(f"The 1st row and 2nd column contains :- ",arr2[0,1]) #used to display the value from 2-D array(1st row and 2nd column)[1,2,3] = row 0 and 1,2,3 column 0,1,2
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr3[1, 4]) #used to display the value from 2-D array(1st row and 2nd column)

#3-D Array
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr4[0,2,1]) #used to display the value from 3-D array(0th index, 2nd row and 1st column)
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr5[0,1,2]) #used to display the value from 3-D array(0th index, 1st row and 2nd column)

#Negative Indexing
arr6 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr6[1,-2]) #display the value 9
print(arr6[0,-4]) #display the value 2

1
2
7
The 1st row and 2nd column contains :-  2
5th element on 2nd row:  10
8
6
9
2


In [ ]:
import numpy as np

#1-D Array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:4]) #used to display 2,3,4
print(arr[4:]) #used to display from 5-10
print(arr[:4]) #used to display from 1-4
print(arr[-3:-1]) #used to display 8 and 9
print(arr[1::2]) #used to display all even values
print(arr[0::2]) #used to display all odd values

#2-D Array
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[1,1:4]) #used to display 7,8,9
print(arr1[0:2,2]) #used to display 3 and 8
print(arr1[0:,1:4]) #used to display 2,3,4 and 7,8,9



[10 20 30 40]
[10 20 30 40]


In [ ]:
import numpy as np

arr = np.array([1,2,3])
arr1 = np.array(["Apple","Mango","Banana"])
print(arr.dtype) #used to check the datatype(int64)
print(arr1.dtype) #used to check the datatype(U6)


arr2 = np.array([1,2,3,4],dtype = 'S')
arr3 = np.array([1,2,3,4],dtype = 'i4')
print(arr2)
print(arr2.dtype) #used to check the datatype(S1)
print(arr3.dtype) #used to check the datatype(int32)


#changing datatype
arr4 = np.array([1.1,2.1,3.1])
newarr = arr4.astype('i') #convert it to int32
newarr1 =arr4.astype(int) #convert it to int64
print(newarr)
print(newarr.dtype)#used to check the datatype(int32)
print(newarr.dtype)#used to check the datatype(int64)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1
int32
[1 2 3]
int64


In [ ]:
import numpy as np

#Copy
arr = np.array([1,2,3,4,5])
x = arr.copy()#it is used to copy the 'arr' to 'x'
x[0] = (41) #changes 1 to 41(only in x anot arr)
print(arr)
print(x)

#View
arr1 = np.array([1,2,3,4,5])
x1 = arr1.view() #it is used to view the value of 'arr' to 'x'
x1[0] = (42) #changes 1 to 42(changes both)
print(arr1)
print(x1)

[1 2 3 4 5]
[41  2  3  4  5]
[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr =np.array(([1,2,3],[4,5,6])) #rows and then columns
print(arr.shape) #it returns tuple with each index having the number of corresponding elements.

arr1 = np.array([1,2,3,4,5],ndmin=5)
print(f"The Shape of the array is {arr1.shape}")

(2, 3)
The Shape of the array is (1, 1, 1, 1, 5)


In [ ]:
# import numpy as np

# # #Reshape from 1-D to 2-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3) #row and column
print(newarr)

#Reshape from 1-D to 3-D
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr1 =arr1.reshape(2,3,2) #part,row,column
print(newarr1)

#Reshape Unknown dimension(-1)
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newarr2 = arr2.reshape(2,4,-1) #You are allowed to have one "unknown" dimension.Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.Pass -1 as the value, and NumPy will calculate this number for you.
print(newarr2)#-1 automatically calculates it

#Flatterning
arr3 = np.array([[1,2,3],[4,5,6]])
newarr3 = arr3.reshape(-1) #Flattening array means converting a multidimensional array into a 1D array.
print(newarr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

# #1-D
# arr1 = np.array([1,2,3,4,5])
# for x1 in arr1:#for elements
#   print(x1)

# #2-D
# arr2 = np.array([[1,2],[3,4]])
# for x2 in arr2:
#   print(x2)

# for x2 in arr2: #for elements
#   for y2 in x2:
#     print(y2)

# #3-D
# arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
# for x3 in arr3:
#   print(x3)

# for x3 in arr3: #for elements
#   for y3 in x3:
#     for z3 in y3:
#           print(z3)
# #OR
# for x3 in np.nditer(arr3): #instead of using multiple loop, the user can use 'nditer'
#   print(x3)



arr4 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])

print(arr4[::2, :])    # every 2nd row
print(arr4[:, ::2])    # every 2nd column
print(arr4[::-1, ::-1]) #reverse

for x in np.nditer(arr4[::2, ::2]): #first is for row and second is for column
    print(x)


for indx,x in np.ndenumerate(arr4): #for maintaining index with values
  print(indx,x)

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
1
3
9
11
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [ ]:
import numpy as np

#string sorting
arr = np.array(["Cherry","Apple","Banana","Mango"])
print(np.sort(arr)) #sorts the element in alphabetical order

#boolean sorting
arr1 = np.array([True,False,True])
print(np.sort(arr1))

#numerical sorting
arr2 = np.array([4,7,2,4,1,9])
print(np.sort(arr2)) #ascending order

#2-D Array
arr3 = np.array([[3,2,4],[1,7,0]])
print(np.sort(arr3)) #sorts the elements of an array

['Apple' 'Banana' 'Cherry' 'Mango']
[False  True  True]
[1 2 4 4 7 9]
[[2 3 4]
 [0 1 7]]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,4,2,3,6,4,8])
x = np.where(arr == 4)
y = np.where(arr%2==0)
z = np.where(arr%2==1)
print(x)
print(y)
print(z)

arr1 = np.array([1,2,3,5,6,7,8])
z1 = np.searchsorted(arr1,4) #Find the indexes where the value 4 should be inserted:
print(z1)

arr2 = np.array([1, 3, 5, 7])
x2 = np.searchsorted(arr2, [2, 4, 6])  #Find the indexes where the value 2,4,6 should be inserted:
print(x2)

(array([ 3,  6, 10]),)
(array([ 1,  3,  5,  6,  7,  9, 10, 11]),)
(array([0, 2, 4, 8]),)
3
[1 2 3]


In [ ]:
import numpy as np
from numpy import random

ran = np.random.rand(4,2) #used to generate random float numbers (from 0-1) and user can specify the array as well
print(ran)

ran1 = np.random.randn(4,2) #used to generate random float numbers (close to zero[+VE OR -VE]) and user can specify the array as well
print(ran1)

ran2 = np.random.randint(1,100,20) #used to generate random integer value between 1-100 that to 20
print(ran2)

ran3 = np.random.randint(200,size = (3,5)) #creates an array of 3 rows and 5 columns from 200
print(ran3)


x = random.choice([3,5,7,9]) #selects any random number from the mentioned values
print(x)

y = random.choice([0,2,4,6,8],size = (1,2)) #creates array from the values specified above
print(y)

z = random.choice([3,5,7,9],p = (0.1,0.3,0.4,0.2),size = (4,4)) #used to create an array using the help of probability
print(z)

alpha = np.array([1,2,3,4,5])
random.shuffle(alpha) #shuffle is used to rearrange the value of array
#or
random.permutation(alpha) #permutation is used to rearrange the value of array
print(alpha)

[[0.6268345  0.31623449]
 [0.25680009 0.68567023]
 [0.45527677 0.43350497]
 [0.45303637 0.09778425]]
[[ 0.09557543 -0.38453127]
 [-0.40729827  0.41487027]
 [ 2.24866169  0.58043634]
 [ 1.54851083  1.49079116]]
[75 93 89 94 26 79 70 81 87 81 29 11 87 79 18 32 50 13 64 39]
[[166  67 186 139  24]
 [146 126 136 128 152]
 [ 29 136 101 130  89]]
9
[[4 2]]
[[5 9 5 5]
 [9 9 9 9]
 [7 9 5 7]
 [3 3 5 7]]
[4 3 5 1 2]


In [ ]:
import numpy as np
x = int(input("enter the value"))
x1 = np.array([1,2,3,4,5,6])
newx = np.array_split(x1,x) #it is used to split the array
print(newx)

random = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
random1 = np.array_split(random,3) #used to split 2-D arrays
print(random1)

enter the value6
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
